# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef18088336aa5dba87af618d380833c7f0b22aa29249c76ea675c88019e87585cc25f3ddbd520bfa9a0a79d169ea7574ed6b0fdf663855885077f18e1e97b9c6

test:
  secret_key_base: 6a10fe40313896d33225e8dc43b4b9b962e3a3561b6adc37a3815cc32dce58721cba3779477b63da6e8edeaa847702a955ebeb9304e95b82622e4c95195b5d4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
